replicaCount: 1

image:
  repository: ghcr.io/maibornwolff/hybrid-cloud-amqp-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

imagePullSecrets: []
nameOverride: "hybrid-cloud-amqp-operator"
fullnameOverride: "hybrid-cloud-amqp-operator"

serviceAccount:
  # Specifies whether a service account with permissions should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  name: null
  # This is required if the operator should install rabbitmq instaces, can be disabled if you only use the Azure ServiceBus backend
  clusterAdmin: true

# Operator config.yaml
operatorConfig: |
  backend: rabbitmq

# The name of a secret whose data will be provided to the operator as environment variables (using the envFrom mechanism)
# Use this to provide sensitive information like azure credentials to the operator
envSecret: null

# A list of environment variables (with name, value) to provide to the operator
extraEnv: []

# List of volumes to mount into the operator pod
volumes: []
# List of volume mounts for the operator pod
volumeMounts: []

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

pod:
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP

  livenessProbe:
    httpGet:
      path: /healthz
      port: http
  readinessProbe:
    httpGet:
      path: /healthz
      port: http
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

service:
  type: ClusterIP
  port: 80
  targetPort: http

nodeSelector: {}

tolerations: []

affinity: {}

strategy:
  type: Recreate

prometheus:
  enabled: true
  portName: metrics
  port: 8081
  scrapeInterval: 30s